name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: jamieastley/actions/.github/workflows/go_release.yml@master
    with:
      go-version: "1.19.2"
      github-token: ${{ secrets.GITHUB_TOKEN }}
